# Default values for semantic-sonnenschirm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

applications:
  - name: semantic-sonnenschirm
    repoURL: https://https://gitlab.consulting.redhat.com/ai-odyssey-2025/semantic-sonnenschirm.git
    path: helm/semantic-sonnenschirm
    targetRevision: feat/helm-charts
    parameters:
      - name: operators.acm
        value: "false"
    destination:
      namespace: semantic-sonnenschirm

openshiftAi:
  installed: true

sender:

processor:

backend: