---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Red Hat OpenShift AI"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: redhat-ods-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-applications
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "GitOps Operator"
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-gitops-operator